---
# Ansible Playbook for SAP NetWeaver (JAVA) with SAP ASE Sandbox installation

# Use include_role / include_tasks inside Ansible Task block, instead of using roles declaration or Task block with import_roles.
# This ensures Ansible Roles, and the tasks within, will be parsed in sequence instead of parsing at Playbook initialization.


#### Interactive Mode ####
# Interactive mode section can be safely removed without impact if all mandatory variables are provided.
- name: Ansible Play to Interactively gather all mandatory variables
  hosts: localhost
  gather_facts: false
  pre_tasks:

    - name: Block for collection for interactive prompts
      when:
        - sap_playbook_interactive_product is defined and sap_playbook_interactive_product | length > 0
        - sap_playbook_interactive_database is defined and sap_playbook_interactive_database | length > 0
        - sap_playbook_interactive_layout is defined and sap_playbook_interactive_layout | length > 0
      block:
        - name: Check if interactive tasks are available
          ansible.builtin.stat:
            path: optional/interactive/main.yml
          register: sap_playbook_interactive_tasks_availability
          ignore_errors: true

        - name: Execute collection of interactive inputs
          ansible.builtin.include_tasks:
            file: optional/interactive/main.yml
          when: sap_playbook_interactive_tasks_availability.stat.exists


- name: Ansible Play to validate the variables
  hosts: localhost
  # gather_facts is required for loop over hostvars
  tasks:

    - name: Assert that the variable 'sap_vm_provision_iac_type' is valid
      ansible.builtin.assert:
        that:
          - sap_vm_provision_iac_type is defined
          - sap_vm_provision_iac_type in ['ansible', 'ansible_to_terraform', 'existing_hosts']
        fail_msg: |
          The variable 'sap_vm_provision_iac_type' is undefined or invalid.
          Available options: ansible, ansible_to_terraform, existing_hosts

    - name: Assert that the variable 'sap_vm_provision_iac_platform' is valid
      ansible.builtin.assert:
        that:
          - sap_vm_provision_iac_platform is defined
          - sap_vm_provision_iac_platform in
            ['aws_ec2_vs', 'gcp_ce_vm', 'msazure_vm', 'ibmcloud_powervs', 'ibmcloud_vs', 'ibmpowervm_vm', 'kubevirt_vm', 'ovirt_vm', 'vmware_vm', 'existing_hosts']
        fail_msg: |
          The variable 'sap_vm_provision_iac_platform' is undefined or invalid.
          Available options: aws_ec2_vs, gcp_ce_vm, msazure_vm, ibmcloud_powervs, ibmcloud_vs, ibmpowervm_vm, kubevirt_vm, ovirt_vm, vmware_vm, existing_hosts

    # Ignore registered vars and sap_swpm hostnames which could contain hostvars.
    - name: Prepare list of SAP variables for validation  # noqa: ignore-errors
      ansible.builtin.set_fact:
        sap_playbook_dictionary_vars:
          "{{ dict(sap_playbook_dictionary_vars | zip(lookup('ansible.builtin.vars', *sap_playbook_dictionary_vars))) }}"
      vars:
        sap_playbook_dictionary_vars:
          "{{ lookup('ansible.builtin.varnames', '^(__)?sap_', wantlist=true)
              | reject('search', '(^(__)?sap_swpm_.*_hostname$)|(.*_register$)')
              | reject('in', ['sap_swpm_db_host'])
              | list }}"
      no_log: true
      ignore_errors: true

    - name: Identify variables with placeholder values or empty passwords  # noqa: ignore-errors
      ansible.builtin.set_fact:
        sap_playbook_placeholder_vars:
          "{{ sap_playbook_dictionary_vars | dict2items
              | selectattr('value', 'equalto', 'ENTER_STRING_VALUE_HERE') | map(attribute='key') | list }}"

        sap_playbook_empty_password_vars:
          "{{ sap_playbook_dictionary_vars | dict2items | selectattr('key', 'search', 'password')
              | selectattr('value', 'in', [none, '']) | map(attribute='key') | list }}"
      no_log: true
      ignore_errors: true

    - name: Report SAP variable validation failures
      ansible.builtin.fail:
        msg: |
          Please address the following issues before re-running the playbook:
          {% if sap_playbook_placeholder_vars | length > 0 %}
          - Placeholder values found for variable(s):
            {% for item in sap_playbook_placeholder_vars %}
            {{ item }}
            {% endfor %}

          {% endif %}
          {% if sap_playbook_empty_password_vars | length > 0 %}
          - Empty or invalid values found for password variable(s):
            {% for item in sap_playbook_empty_password_vars %}
            {{ item }}
            {% endfor %}
          {% endif %}
      when:
        - sap_playbook_placeholder_vars | d([]) | length > 0 or sap_playbook_empty_password_vars | d([]) | length > 0


#### Begin Infrastructure-as-Code provisioning ####
- name: Ansible Play to create dynamic inventory group for provisioning
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Block to prepare inventory for provisioning
      when:
        - sap_vm_provision_iac_type in ['ansible', 'ansible_to_terraform']
        - sap_vm_provision_iac_platform != 'existing_hosts'
      vars:
        __sap_playbook_host_dictionary_name: "{{ 'sap_vm_provision_' ~ sap_vm_provision_iac_platform ~ '_host_specifications_dictionary' }}"
      block:
        - name: Assert that the variable {{ __sap_playbook_host_dictionary_name }} is defined and valid
          ansible.builtin.assert:
            that:
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name) is defined
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name) is mapping
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name) | length > 0
            fail_msg: |
              The variable {{ __sap_playbook_host_dictionary_name }} is undefined or invalid.
              It must be a non-empty dictionary.

        - name: Assert that the variable 'sap_vm_provision_host_specification_plan' is defined and valid
          ansible.builtin.assert:
            that:
              - sap_vm_provision_host_specification_plan is defined
              - sap_vm_provision_host_specification_plan is string
              - sap_vm_provision_host_specification_plan | trim | length > 0
            fail_msg: |
              The variable 'sap_vm_provision_host_specification_plan' is undefined or invalid.
              It must be a non-empty string.

        - name: Assert that the variable 'sap_vm_provision_host_specification_plan' is present in a dictionary
          ansible.builtin.assert:
            that:
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name)[sap_vm_provision_host_specification_plan] is defined
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name)[sap_vm_provision_host_specification_plan] is mapping
              - lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name)[sap_vm_provision_host_specification_plan] | length > 0
            fail_msg: |
              The variable 'sap_vm_provision_host_specification_plan' is not present in a dictionary {{ __sap_playbook_host_dictionary_name }}.

        - name: Create dynamic inventory group for Ansible Role sap_vm_provision
          ansible.builtin.add_host:
            name: "{{ item }}"
            group: sap_vm_provision_target_inventory_group
          loop: "{{ lookup('ansible.builtin.vars', __sap_playbook_host_dictionary_name)[sap_vm_provision_host_specification_plan].keys() }}"


# Ansible Play target hosts pattern, use Inventory Group created by previous Ansible Task (add_host)
- name: Ansible Play to provision hosts for SAP
  hosts: sap_vm_provision_target_inventory_group
  gather_facts: false
  tasks:

    # Ensure that all sap_* or __sap_* variables set in Interactive Mode are appended to the target inventory Group
    - name: Assign all relevant facts from execution node before provisioning  # noqa: ignore-errors
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
        cacheable: true
      loop: "{{ hostvars['localhost'] | dict2items | selectattr('key', 'match', '^(__)?sap_') | list }}"
      when:
        - sap_playbook_interactive_product is defined and sap_playbook_interactive_product | length > 0
        - sap_playbook_interactive_database is defined and sap_playbook_interactive_database | length > 0
        - sap_playbook_interactive_layout is defined and sap_playbook_interactive_layout | length > 0
        - vars[item.key] is undefined
      no_log: true
      ignore_errors: true  # Ignore errors for variables defined later during runtime

    - name: Execute Ansible Role sap_vm_provision
      ansible.builtin.include_role:
        name: community.sap_infrastructure.sap_vm_provision
      when:
        - sap_vm_provision_iac_type in ['ansible', 'ansible_to_terraform']
        - sap_vm_provision_iac_platform != 'existing_hosts'

- name: Ansible Play to set sap variables on provisioned hosts
  hosts: sap_vm_provision_target_inventory_group  # noqa: ignore-errors
  gather_facts: false
  tasks:

    - name: Assign all relevant facts from execution node after provisioning  # noqa: ignore-errors
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
        cacheable: true
      loop: "{{ hostvars['localhost'] | dict2items | selectattr('key', 'match', '^(__)?sap_') | list }}"
      when:
        - sap_playbook_interactive_product is defined and sap_playbook_interactive_product | length > 0
        - sap_playbook_interactive_database is defined and sap_playbook_interactive_database | length > 0
        - sap_playbook_interactive_layout is defined and sap_playbook_interactive_layout | length > 0
        - vars[item.key] is undefined
      no_log: true
      ignore_errors: true  # Ignore errors for variables defined later during runtime


#### VM storage filesystem setup ####
- name: Ansible Play for hosts storage setup
  hosts: nwas_pas
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:

    # Use inventory_hostname_short to retrieve host specification from the dictionary.
    # While ansible_hostname will work for Ansible only, using Ansible>Terraform may see ansible_hostname as 'localhost' and fail
    - name: Execute Ansible Role sap_storage_setup
      ansible.builtin.include_role:
        name: community.sap_install.sap_storage_setup
      vars:
        sap_playbook_host_dictionary_hostname:
          "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform
           + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][inventory_hostname_short] }}"
        sap_storage_setup_sid: "{{ sap_playbook_host_dictionary_hostname.get('sap_storage_setup_sid', (sap_system_sid | d(''))) }}"
        sap_storage_setup_nwas_java_scs_instance_nr:
          "{{ sap_playbook_host_dictionary_hostname.get('sap_storage_setup_nwas_java_scs_instance_nr', (sap_system_nwas_java_scs_instance_nr | d(''))) }}"
        sap_storage_setup_nwas_java_ci_instance_nr:
          "{{ sap_playbook_host_dictionary_hostname.get('sap_storage_setup_nwas_java_ci_instance_nr', (sap_system_nwas_abap_pas_instance_nr | d(''))) }}"
        sap_storage_setup_host_type: "{{ sap_playbook_host_dictionary_hostname.get('sap_storage_setup_host_type', []) }}"
      when: sap_playbook_host_dictionary_hostname is defined


#### Begin downloading SAP software installation media to hosts ####
- name: Ansible Play for downloading installation media
  hosts: nwas_pas
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:

    # SAP software download will only occur if the 'community.sap_launchpad' collection is installed.
    # Playbook will continue without the collection, assuming SAP software is already available.
    - name: Check availability of sap_launchpad collection on execution node
      delegate_to: localhost
      become: false  # Enables usage of Python VENV
      ansible.builtin.command:
        cmd: ansible-galaxy collection list
      register: sap_playbook_collection_list_output

    - name: Execute Ansible Role sap_software_download
      ansible.builtin.include_role:
        name: community.sap_launchpad.sap_software_download
      vars:
        sap_software_download_suser_id: "{{ sap_id_user }}"
        sap_software_download_suser_password: "{{ sap_id_user_password }}"
        sap_software_download_directory: "{{ sap_install_media_detect_source_directory }}"
        sap_software_download_deduplicate: first
        sap_software_download_files: "{{ sap_software_install_dictionary[sap_software_product]
          ['softwarecenter_search_list_' ~ ansible_architecture] }}"
      when: sap_playbook_collection_list_output.stdout_lines | select('search', 'community.sap_launchpad') | length > 0


#### Begin SAP software hosts preparation ####
- name: Ansible Play for preparing all SAP software hosts
  hosts: nwas_pas
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_general_preconfigure
      ansible.builtin.include_role:
        name: community.sap_install.sap_general_preconfigure

    - name: Execute Ansible Role sap_netweaver_preconfigure
      ansible.builtin.include_role:
        name: community.sap_install.sap_netweaver_preconfigure


#### Begin SAP software installations ####
- name: Ansible Play for SAP ASE Database Server and SAP NetWeaver Application Server (JAVA) installation - JAVA Central Services (SCS) and Primary Application Server (PAS)
  hosts: nwas_pas
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: false
        sap_install_media_detect_db: "sapase"
        sap_install_media_detect_db_client: "sapase"
        sap_install_media_detect_export: "sapnwas_java"

    # Install SAP ASE and SAP NetWeaver (JAVA) via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_software_product }}"
